### ISSUE TITLE
Automatic help text generation

### ISSUE THREAD

**Issue by musaprg** [PrajwalCH/yazap#1]
Hi, thank you for creating this awesome library.

I have one feature request. (it could have already been considered though)
It would be more helpful for users to have automatic help text generation based on configured flags.

Yazap already has a `Command.newWithHelpTxt` function to set the `about` field, but currently, it doesn't have any way to output its information except for directly reading `about` and constructing our own help message by ourselves.

**Comment by PrajwalCH** [comment]
Hey,
It will be definitely implemented 😁 but after v0.1.0  release. The only thing left is to implement **arg validation and logging errors** plus updating/improving README docs and example after that i will start to implement **generating help ** and others.

**Comment by PrajwalCH** [comment]
> Hi, thank you for creating this awesome library.
> 
> I have one feature request. (it could have already been considered though)
> It would be more helpful for users to have automatic help text generation based on configured flags.
> 
> Yazap already has a `Command.newWithHelpTxt` function to set the `about` field, but currently, it doesn't have any way to output its information except for directly reading `about` and constructing our own help message by ourselves.

Now auto help message is implemented on a4df0eb2c953266de8c13a16b6e824f1949f7867. I forget to mention this issue on commit therefore leaving a comment here.
