### ISSUE TITLE
Sub-commands with no values will never match

### ISSUE THREAD

**Issue by erri120** [prajwalch/yazap#23]
Given the following structure:

```
program foo bar
```

```zig
const matches = try app.parseProcess(); // works fine
const fooMatches = matches.subcommandMatches("foo"); // works fine
const barMatches = fooMatches.subcommandMatches("bar"); // fails
```

Although `fooMatches.subcommand` is non-null and `.name` is equal to `bar`, `subcommandMatches` still returns `null` because `bar` didn't have any arguments.

This is an issue with `subcommandMatches`, because it returns `?ArgMatches`, even if `foo` has the `bar` sub-command, the method returns `subcmd.matches` which will be `null` if `bar` doesn't have any arguments or further sub-commands.

This behavior should be different. The easiest solution is to update this:

https://github.com/prajwalch/yazap/blob/55444b9d1a3688b11c47adeef750e7c80a03bae3/src/Parser.zig#L444-L446

If the sub-command doesn't take any value, `arg_matches` should be set to a non-null value instead of `null`. Probably some empty value.

**Comment by prajwalch** [comment]
Fix is now available :)
