### ISSUE TITLE
Missing newline when logging `ParseError.CommandSubcommandNotProvided`

### ISSUE THREAD

**Issue by thenester** [prajwalch/yazap#24]
Hello,

First of all, thank you for the handy library!

I encountered a really minor thing to improve related to error logging. When the `ParseError.CommandSubcommandNotProvided` is logged, the `\n` is missed at the end of the log format in contrast to all other similar places.

https://github.com/prajwalch/yazap/blob/f7308097f9e9ccb0a523762372f53755aa1b57c2/src/error.zig#L82

It would be good to add a missing `\n` so that errors logging style is consistent.

Thanks.

**Comment by prajwalch** [comment]
Hi, patch is now available :)
