### ISSUE TITLE
`multiValuesOption` results in a `singleValueOption` when provided with only one value

### ISSUE THREAD

**Issue by fardragon** [prajwalch/yazap#25]
Hi,

I've just encountered some confusing (at least in my opinion) behaviour. When an option is declared as multi-value the resulting matched argument can still be of the `.single` variant, which makes it inconvenient to use, because you have to check for values using `getMultiValues` and then if that returns null (and it will, because the argument is `.single`)  `getSingleValue`. 

Reproduction example:
```zig
const std = @import("std");
const yazap = @import("yazap");

const App = yazap.App;
const Arg = yazap.Arg;

pub fn main() anyerror!void {
    var app = App.init(std.heap.page_allocator, "repro", null);
    defer app.deinit();

    var repro = app.rootCommand();

    try repro.addArg(Arg.multiValuesOption("repro", 'r', null, 5));

    const matches = try app.parseProcess();

    if (matches.args.get("repro")) |arg| {
        std.debug.print("Argument is single: {} is many: {}\r\n", .{ arg.isSingle(), arg.isMany() });
    }
}
```

Running this on zig 0.13.0 and latest yazap commit:
```
~/Workspace/yazap-repro via ↯ v0.13.0 
❯ zig build run -- --repro one    
Argument is single: true is many: false

~/Workspace/yazap-repro via ↯ v0.13.0 
❯ zig build run -- --repro one two
Argument is single: false is many: true
```

I'd expect the MatchedArgValue union to be `.many` in both cases and just return a slice with one element in the first case. I can try fixing this if you're open to PRs. Alternatively, if this is the desired behaviour, then I'd suggest adjusting the example at https://github.com/prajwalch/yazap/blob/main/src/arg_matches.zig#L185 to indicate that it's needed to check for both cases.

**Comment by fardragon** [comment]
I've noticed that even after adjusting one of the tests to only provide single argument, the test still passes:
```zig
test "Option that takes many/multiple values provided with single value" {
    var app = App.init(allocator, "clang", null);
    errdefer app.deinit();

    var srcs = Arg.init("sources", null);
    srcs.setShortName('s');
    srcs.setValuesDelimiter(":");
    srcs.setProperty(.takes_value);
    srcs.setProperty(.takes_multiple_values);

    // ex: clang sources...
    try app.rootCommand().addArg(srcs);
    const matches = try app.parseFrom(&.{ "-s", "f1" });

    try testing.expectEqual(@as(usize, 1), matches.getMultiValues("sources").?.len);

    app.deinit();
}
```

But changing it to use the multiValuesOption makes it crash, because `getMultiValues` returns null
```zig
test "Option that takes many/multiple values provided with single value" {
    var app = App.init(allocator, "clang", null);
    errdefer app.deinit();

    const srcs = Arg.multiValuesOption("sources", 's', null, 128);

    // ex: clang sources...
    try app.rootCommand().addArg(srcs);
    const matches = try app.parseFrom(&.{ "-s", "f1" });

    try testing.expectEqual(@as(usize, 1), matches.getMultiValues("sources").?.len);

    app.deinit();
}
```

I believe the difference is that `multiValuesOption` doesn't set the `.takes_multiple_values` which seems weird. In the first test the parser code takes this early return here https://github.com/prajwalch/yazap/blob/c9ec8d424335efa431998a6862a8dcf0bd54bd12/src/Parser.zig#L267  and in the second case it doesn't and goes through to here https://github.com/prajwalch/yazap/blob/c9ec8d424335efa431998a6862a8dcf0bd54bd12/src/Parser.zig#L280 and returns the argument as `.single`.  Maybe it's just the case of changing or adding to the properties set in `multiValuesOption`, but I'm having trouble following the early return logic in `parseOptionValue`

**Comment by prajwalch** [comment]
I believe this is happening because of this code:
https://github.com/prajwalch/yazap/blob/c9ec8d424335efa431998a6862a8dcf0bd54bd12/src/Parser.zig#L277-L284

The code checks whether there is only a single value provided or not, if it is indeed only a single value, it blindly assumes the `arg` is a `singleValueOption` without checking the `.takes_multiple_values` property.

We can fix this by adding a second condition `!arg.hasProperty(.takes_multiple_values)`.

You can send the PR and I will merge it. :)
